// Code generated by slice-converter; DO NOT EDIT.
// See github.com/bombsimon/gorm-bulk
package examples

// MyTypePtrSliceToInterfaceSlice returns an interface slice with MyTypes.
func MyTypePtrSliceToInterfaceSlice(ts []*MyType) []interface{} {
	var is = make([]interface{}, len(ts))

	for i := range ts {
		is[i] = ts[i]
	}

	return is
}

// MyTypeSliceToInterfaceSlice returns an interface slice with MyTypes.
func MyTypeSliceToInterfaceSlice(ts []MyType) []interface{} {
	var is = make([]interface{}, len(ts))

	for i := range ts {
		is[i] = ts[i]
	}

	return is
}
